export const url = [
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/abaddon.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/alchemist.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ancient_apparition.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/antimage.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/arc_warden.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/axe.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bane.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/batrider.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/beastmaster.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bloodseeker.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bounty_hunter.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/brewmaster.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bristleback.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/broodmother.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/centaur.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/chaos_knight.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/chen.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/clinkz.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/rattletrap.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/crystal_maiden.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dark_seer.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dark_willow.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dawnbreaker.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dazzle.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/death_prophet.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/disruptor.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/doom_bringer.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dragon_knight.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/drow_ranger.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/earth_spirit.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/earthshaker.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/elder_titan.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ember_spirit.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/enchantress.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/enigma.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/faceless_void.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/grimstroke.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/gyrocopter.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/hoodwink.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/huskar.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/invoker.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/wisp.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/jakiro.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/juggernaut.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/keeper_of_the_light.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/kunkka.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/legion_commander.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/leshrac.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lich.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/life_stealer.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lina.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lion.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lone_druid.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/luna.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lycan.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/magnataur.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/marci.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/mars.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/medusa.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/meepo.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/mirana.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/monkey_king.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/morphling.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/muerta.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/naga_siren.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/furion.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/necrolyte.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/night_stalker.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/nyx_assassin.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ogre_magi.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/omniknight.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/oracle.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/obsidian_destroyer.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pangolier.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phantom_assassin.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phantom_lancer.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phoenix.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/primal_beast.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/puck.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pudge.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pugna.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/queenofpain.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/razor.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/riki.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/rubick.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sand_king.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shadow_demon.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/nevermore.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shadow_shaman.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/silencer.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/skywrath_mage.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/slardar.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/slark.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/snapfire.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sniper.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/spectre.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/spirit_breaker.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/storm_spirit.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sven.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/techies.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/templar_assassin.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/terrorblade.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tidehunter.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shredder.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tinker.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tiny.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/treant.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/troll_warlord.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tusk.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/abyssal_underlord.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/undying.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ursa.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/vengefulspirit.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/venomancer.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/viper.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/visage.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/void_spirit.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/warlock.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/weaver.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/windrunner.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/winter_wyvern.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/witch_doctor.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/skeleton_king.png\")",
    "url(\"https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/zuus.png\")"
]



export const heroes = [
    "Abaddon",
    "Alchemist",
    "Ancient Apparition",
    "Anti-Mage",
    "Arc Warden",
    "Axe",
    "Bane",
    "Batrider",
    "Beastmaster",
    "Bloodseeker",
    "Bounty Hunter",
    "Brewmaster",
    "Bristleback",
    "Broodmother",
    "Centaur Warrunner",
    "Chaos Knight",
    "Chen",
    "Clinkz",
    "Clockwerk",
    "Crystal Maiden",
    "Dark Seer",
    "Dark Willow",
    "Dawnbreaker",
    "Dazzle",
    "Death Prophet",
    "Disruptor",
    "Doom",
    "Dragon Knight",
    "Drow Ranger",
    "Earth Spirit",
    "Earthshaker",
    "Elder Titan",
    "Ember Spirit",
    "Enchantress",
    "Enigma",
    "Faceless Void",
    "Grimstroke",
    "Gyrocopter",
    "Hoodwink",
    "Huskar",
    "Invoker",
    "Io",
    "Jakiro",
    "Juggernaut",
    "Keeper of the Light",
    "Kunkka",
    "Legion Commander",
    "Leshrac",
    "Lich",
    "Lifestealer",
    "Lina",
    "Lion",
    "Lone Druid",
    "Luna",
    "Lycan",
    "Magnus",
    "Marci",
    "Mars",
    "Medusa",
    "Meepo",
    "Mirana",
    "Monkey King",
    "Morphling",
    "Naga Siren",
    "Nature's Prophet",
    "Necrophos",
    "Night Stalker",
    "Nyx Assassin",
    "Ogre Magi",
    "Omniknight",
    "Oracle",
    "Outworld Destroyer",
    "Pangolier",
    "Phantom Assassin",
    "Phantom Lancer",
    "Phoenix",
    "Puck",
    "Pudge",
    "Pugna",
    "Queen of Pain",
    "Razor",
    "Riki",
    "Rubick",
    "Sand King",
    "Shadow Demon",
    "Shadow Fiend",
    "Shadow Shaman",
    "Silencer",
    "Skywrath Mage",
    "Slardar",
    "Slark",
    "Snapfire",
    "Sniper",
    "Spectre",
    "Spirit Breaker",
    "Storm Spirit",
    "Sven",
    "Techies",
    "Templar Assassin",
    "Terrorblade",
    "Tidehunter",
    "Timbersaw",
    "Tinker",
    "Tiny",
    "Treant Protector",
    "Troll Warlord",
    "Tusk",
    "Underlord",
    "Undying",
    "Ursa",
    "Vengeful Spirit",
    "Venomancer",
    "Viper",
    "Visage",
    "Void Spirit",
    "Warlock",
    "Weaver",
    "Windranger",
    "Winter Wyvern",
    "Witch Doctor",
    "Wraith King",
    "Zeus",
    ""
]